[2021-09-08 10:43:18,797] INFO [test_1: test_info.py, 14] 当前使用环境为pro
[2021-09-08 10:43:39,898] ERROR [test_1: test_info.py, 22] 你的用例1报错啦
